### ISSUE TITLE
scrwipe eats up a huge chunk of my cpu, and just kinda chills in the backround hogging resources until I manually close it

### ISSUE THREAD

**Issue by Flammable-Duck** [vifino/artsy#1]
Really fun program otherwise, lol.

**Comment by vifino** [comment]
Huh?
There is no infinite loop and it only does printing to stdout with a few sleeps, it should be roughly 0.5 second long animation every time.

Can I get more info? What platform, what terminal? How big is your terminal? (`stty size`)
I've never experienced anything like that.

**Comment by Flammable-Duck** [comment]
Ok, so I tried it again to get some screenshots for you, but it didn't happen for some reason? I'm going to assume that I was doing something stupid before. Sorry to bother you.

**Comment by vifino** [comment]
Don't worry. Enjoy!

By the way, I use `scrwipe` mostly bound to Ctrl-L, in zsh that is easily doable like this:
```
scrwipe_widget() {
	scrwipe && zle clear-screen
}
zle -N scrwipe_widget
bindkey "^L" scrwipe_widget
```

**Comment by Flammable-Duck** [comment]
Thanks, I'll try that :)
